//# DO NOT MODIFY.
//# This is autogenerated by `ySwiftCodeUpdater`(https://github.com/YOCKOW/ySwiftCodeUpdater).
//# Please see documents in this project to learn how to regenerate.
//# The material(s) to generate this file was/were obtained from below:
//
// URL: http://Bot.YOCKOW.jp/-/lastModified/20191128000000
// Last-Modified: 2019-11-28T00:00:00Z
//
// URL: https://bot.yockow.jp/-/eTag/strong:test
// ETag: "test"

struct MyTest {
  var number: Int = 0
}
