/* *************************************************************************************************
 CodeUpdater.swift
  © 2019,2026 YOCKOW.
    Licensed under MIT License.
    See "LICENSE.txt" for more information.
************************************************************************************************ */

import Foundation
import NetworkGear
import TemporaryFile
import yExtensions

private let _HEADER = """
//# DO NOT MODIFY.
//# This is autogenerated by `ySwiftCodeUpdater`(https://github.com/YOCKOW/ySwiftCodeUpdater).
//# Please see documents in this project to learn how to regenerate.
//# The material(s) to generate this file was/were obtained from below:

""".data(using: .utf8)!


private extension CodeUpdaterDelegate {
  func _outrightConvert(inContext context: JobManager.Context) async throws -> Data {
    let sourceURLs = self.sourceURLs

    let interms = try await context.do(
      "Preparing data conversion..."
    ) { _ in
      return try await withThrowingTaskGroup(
        of: IntermediateDataContainer<Self.IntermediateDataType>.self,
        returning: Array<IntermediateDataContainer<Self.IntermediateDataType>>.self
      ) { group in
        for url in sourceURLs {
          group.addTask {
            var interm = try await self.prepare(sourceURL: url)
            interm.sourceURL = url
            return interm
          }
        }

        let dict = try await group.reduce(
          into: Dictionary<URL, IntermediateDataContainer<Self.IntermediateDataType>>()
        ){
          $0[$1.sourceURL] = $1
        }

        var result = Array<IntermediateDataContainer<Self.IntermediateDataType>>()
        for url in sourceURLs {
          result.append(dict[url]!)
        }
        return result
      }
    }

    return try await context.do(
      "Converting the intermediate data..."
    ) { _ in
      return try await self.convert(interms)
    }
  }
}

public final class CodeUpdater: @unchecked Sendable {
  private let _delegate: any CodeUpdaterDelegate
  public var identifier: String { return self._delegate.identifier }
  public var sourceURLs: Array<URL> { return self._delegate.sourceURLs }
  public var destinationURL: URL { return self._delegate.destinationURL }

  public internal(set) var forcesToUpdate: Bool

  private actor _ConvertedData {
    unowned let owner: CodeUpdater
    init(owner: CodeUpdater) {
      self.owner = owner
    }

    private var _convertedData: Data? = nil
    var convertedData: Data {
      get async throws {
        if let convertedData = self._convertedData {
          return convertedData
        }

        let convertedData = try await JobManager.default.do(
          "Starting data conversion...",
          jobID: owner.identifier
        ) { ctx in
          return try await owner._delegate._outrightConvert(inContext: ctx)
        }
        self._convertedData = convertedData
        return convertedData
      }
    }
  }
  private lazy var _convertedData: _ConvertedData = .init(owner: self)
  public var convertedData: Data {
    get async throws {
      return try await _convertedData.convertedData
    }
  }
  
  public init<D>(delegate: D, forcesToUpdate: Bool = false) where D: CodeUpdaterDelegate {
    precondition(delegate.destinationURL.isFileURL, "Destination must be local.")
    self._delegate = delegate
    self.forcesToUpdate = forcesToUpdate
  }
  
  public func shouldUpdate() async throws -> Bool {
    return try await JobManager.default.do(
      "Determining whether to update...",
      jobID: self.identifier
    ) { (context) -> Bool in
      if !FileManager.default.fileExists(atPath: self._delegate.destinationURL.path) {
        return true
      }

      let info = try _TargetFileInfo(fileAt: self._delegate.destinationURL)
      for sourceURL in self._delegate.sourceURLs {
        if !info.containsInfo(for: sourceURL) { return true }
        switch (info.lastModifiedDate(for: sourceURL), info.eTag(for: sourceURL)) {
        case (nil, nil):
          return true
        case (let dest_lastModified?, nil):
          guard let source_lastModified = try await context.lastModifiedDate(of: sourceURL) else {
            return true
          }
          if dest_lastModified < source_lastModified { return true }
        case (nil, let dest_ETag?):
          guard let source_ETag = try await context.eTag(of: sourceURL) else {
            return true
          }
          if !(dest_ETag =~ source_ETag) { return true }
        case (let dest_lastModified?, let dest_ETag?):
          guard
            let source_lastModified = try await context.lastModifiedDate(of: sourceURL),
            let source_ETag = try await context.eTag(of: sourceURL)
          else {
              return true
          }
          if dest_lastModified < source_lastModified || !(dest_ETag =~ source_ETag) { return true }
        }
      }
      return false
    }
  }

  public func update() async throws {
    let destURL = self._delegate.destinationURL
    let destPath = destURL.path
    try await JobManager.default.do(
      "Updating file at '\(destPath)'...",
      jobID: identifier
    ) { context in
      let forcesToUpdate = self.forcesToUpdate
      let shouldUpdate = try await self.shouldUpdate()
      if !forcesToUpdate && !shouldUpdate {
        context.view(message: "File at \(destPath) is already up-to-date.")
        return
      }

      let data = try await convertedData
      let temporaryFile = HybridTemporaryFile()
      defer { try? temporaryFile.close() }
      try await context.do("Writing the data to temporary file...") { subcontext in
        try temporaryFile.write(contentsOf: _HEADER)
        for url in self._delegate.sourceURLs {
          try temporaryFile.write(string: "//\n")
          try temporaryFile.write(string: "// URL: \(url.absoluteURL)\n")
          if let lastModified = try await subcontext.lastModifiedDate(of: url) {
            try temporaryFile.write(string: "// Last-Modified: \(lastModified.iso8601String)\n")
          }
          if let eTag = try await subcontext.eTag(of: url) {
            try temporaryFile.write(string: "// ETag: \(eTag.description)\n")
          }
        }
        temporaryFile.write("\n")
        try temporaryFile.write(contentsOf: data)
      }
      
      let backupURL = destURL.appendingPathExtension("old")
      try await context.do("Copying the temporary file to the destination...") { _ in
        if destURL.isExistingLocalFile {
          try FileManager.default.moveItem(at: destURL, to: backupURL)
        }
        try temporaryFile.copy(to: destURL)
        if backupURL.isExistingLocalFile {
          try FileManager.default.removeItem(at: backupURL)
        }
      }
    }
  }
}
