#if !canImport(ObjectiveC)
import XCTest

extension CSVTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CSVTests = [
        ("test_rows", test_rows),
    ]
}

extension SwiftKeywordsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftKeywordsTests = [
        ("test_identifier", test_identifier),
        ("test_keywords", test_keywords),
    ]
}

extension TargetFileInfoTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TargetFileInfoTests = [
        ("test_info", test_info),
    ]
}

extension yCodeUpdaterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__yCodeUpdaterTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CSVTests.__allTests__CSVTests),
        testCase(SwiftKeywordsTests.__allTests__SwiftKeywordsTests),
        testCase(TargetFileInfoTests.__allTests__TargetFileInfoTests),
        testCase(yCodeUpdaterTests.__allTests__yCodeUpdaterTests),
    ]
}
#endif
