#if !canImport(ObjectiveC)
import XCTest

extension CSVTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CSVTests = [
        ("test_rows", test_rows),
    ]
}

extension yCodeUpdaterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__yCodeUpdaterTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CSVTests.__allTests__CSVTests),
        testCase(yCodeUpdaterTests.__allTests__yCodeUpdaterTests),
    ]
}
#endif
